import turtle
turtle.color("blue")
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
turtle.color("red")
turtle.begin_fill()
turtle.right(45)
turtle.forward(135)
turtle.right(87)
turtle.forward(145)
turtle.end_fill()
turtle.penup()
turtle.goto(-200,150)
turtle.pendown()
turtle.pensize(5)
turtle.color("")
turtle.begin_fill()
turtle.circle(60)

turtle.end_fill()
turtle.done()
